# trajectory controllers ---------------------------------------
#thor_mang:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
    
  l_arm_shoulder_pitch_joint_controller:
    type: effort_controllers/JointPositionController
    joint: l_arm_shoulder_pitch_joint
    pid: {p: 1000.0, i: 0.01, d: 10.0}
